"""account secret names and universe sources

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-02 22:45:30.149316

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__universe_source",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk__alpaca_connectors__universe_source")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "UniverseSource",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__universe_source__enabled"),
        "alpaca_connectors__universe_source",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__universe_source__symbol"),
        "alpaca_connectors__universe_source",
        ["symbol"],
        unique=False,
    )
    # Preserve any account registrations created before secret-name bindings existed.  The
    # temporary defaults match the names used by the old runtime, then are removed so all future
    # inserts must supply explicit names through the application contract.
    op.add_column(
        "alpaca_connectors__acct_alpaca",
        sa.Column(
            "api_key_secret_name",
            sa.String(length=255),
            nullable=False,
            server_default=sa.text("'ALPACA_API_KEY'"),
        ),
    )
    op.add_column(
        "alpaca_connectors__acct_alpaca",
        sa.Column(
            "secret_key_secret_name",
            sa.String(length=255),
            nullable=False,
            server_default=sa.text("'ALPACA_SECRET_KEY'"),
        ),
    )
    op.alter_column(
        "alpaca_connectors__acct_alpaca",
        "api_key_secret_name",
        server_default=None,
    )
    op.alter_column(
        "alpaca_connectors__acct_alpaca",
        "secret_key_secret_name",
        server_default=None,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__acct_alpaca__api_key_secret_name"),
        "alpaca_connectors__acct_alpaca",
        ["api_key_secret_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__acct_alpaca__secret_key_secret_name"),
        "alpaca_connectors__acct_alpaca",
        ["secret_key_secret_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__alpaca_connectors__acct_alpaca__secret_key_secret_name"),
        table_name="alpaca_connectors__acct_alpaca",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__acct_alpaca__api_key_secret_name"),
        table_name="alpaca_connectors__acct_alpaca",
    )
    op.drop_column("alpaca_connectors__acct_alpaca", "secret_key_secret_name")
    op.drop_column("alpaca_connectors__acct_alpaca", "api_key_secret_name")
    op.drop_index(
        op.f("ix__alpaca_connectors__universe_source__symbol"),
        table_name="alpaca_connectors__universe_source",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__universe_source__enabled"),
        table_name="alpaca_connectors__universe_source",
    )
    op.drop_table("alpaca_connectors__universe_source")
    # ### end Alembic commands ###
