"""asset registration operation progress

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-03 10:06:02.394780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__asset_registration_operation",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("owner_uid", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "uid", name=op.f("pk__alpaca_connectors__asset_registration_operation")
        ),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AssetRegistrationOperation",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__created_at"),
        "alpaca_connectors__asset_registration_operation",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__owner_uid"),
        "alpaca_connectors__asset_registration_operation",
        ["owner_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__status"),
        "alpaca_connectors__asset_registration_operation",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__status"),
        table_name="alpaca_connectors__asset_registration_operation",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__owner_uid"),
        table_name="alpaca_connectors__asset_registration_operation",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_registration_operation__created_at"),
        table_name="alpaca_connectors__asset_registration_operation",
    )
    op.drop_table("alpaca_connectors__asset_registration_operation")
    # ### end Alembic commands ###
