"""add alpaca asset details

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-03 15:44:14.001554

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__asset_alpaca",
        sa.Column("asset_uid", sa.Uuid(), nullable=False),
        sa.Column("alpaca_asset_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("tradable", sa.Boolean(), nullable=False),
        sa.Column("marginable", sa.Boolean(), nullable=True),
        sa.Column("shortable", sa.Boolean(), nullable=True),
        sa.Column("easy_to_borrow", sa.Boolean(), nullable=True),
        sa.Column("fractionable", sa.Boolean(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_uid"],
            ["ms_markets__asset.uid"],
            name=op.f("fk__alpaca_connectors__asset_alpaca__asset_uid__ms_m_123200ccf1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("asset_uid", name=op.f("pk__alpaca_connectors__asset_alpaca")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AlpacaAssetDetails",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_alpaca__asset_class__symbol"),
        "alpaca_connectors__asset_alpaca",
        ["asset_class", "symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_alpaca__exchange"),
        "alpaca_connectors__asset_alpaca",
        ["exchange"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_alpaca__symbol"),
        "alpaca_connectors__asset_alpaca",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__asset_alpaca__alpaca_asset_id"),
        "alpaca_connectors__asset_alpaca",
        ["alpaca_asset_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix__alpaca_connectors__asset_alpaca__alpaca_asset_id"),
        table_name="alpaca_connectors__asset_alpaca",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_alpaca__symbol"),
        table_name="alpaca_connectors__asset_alpaca",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_alpaca__exchange"),
        table_name="alpaca_connectors__asset_alpaca",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_alpaca__asset_class__symbol"),
        table_name="alpaca_connectors__asset_alpaca",
    )
    op.drop_table("alpaca_connectors__asset_alpaca")
    # ### end Alembic commands ###
