"""Asset registration helpers for Alpaca connectors."""

from .alpaca_asset_details import (
    ALPACA_IDENTIFIER_PREFIX,
    AlpacaAssetDetails,
    AlpacaAssetDetailsTable,
    alpaca_details_for_asset_id,
    alpaca_details_for_asset_uid,
    asset_type_from_alpaca_class,
    build_alpaca_unique_identifier,
    parse_alpaca_unique_identifier,
)
from .alpaca_us_equities import (
    AlpacaAssetRecord,
    AlpacaEquityClassificationPass,
    AlpacaEquityRegistrationPlan,
    AlpacaEquityRegistrationResolution,
    AlpacaUsEquity,
    AssetRegistrationProgressCallback,
    OpenFigiMatch,
    RegisteredAlpacaAssetReference,
    build_alpaca_us_equity_registration_plan,
    build_alpaca_us_equity_trading_client,
    classify_alpaca_us_equities,
    fetch_alpaca_us_equities,
    query_openfigi_by_ticker,
    register_alpaca_us_equity_assets,
    resolve_alpaca_us_equity_registration_plan,
)
from .catalog import get_asset, list_assets

__all__ = [
    "ALPACA_IDENTIFIER_PREFIX",
    "AlpacaAssetDetails",
    "AlpacaAssetDetailsTable",
    "AlpacaAssetRecord",
    "AlpacaEquityClassificationPass",
    "AlpacaEquityRegistrationPlan",
    "AssetRegistrationProgressCallback",
    "AlpacaEquityRegistrationResolution",
    "AlpacaUsEquity",
    "OpenFigiMatch",
    "RegisteredAlpacaAssetReference",
    "alpaca_details_for_asset_id",
    "alpaca_details_for_asset_uid",
    "asset_type_from_alpaca_class",
    "build_alpaca_unique_identifier",
    "build_alpaca_us_equity_registration_plan",
    "build_alpaca_us_equity_trading_client",
    "classify_alpaca_us_equities",
    "fetch_alpaca_us_equities",
    "get_asset",
    "list_assets",
    "parse_alpaca_unique_identifier",
    "query_openfigi_by_ticker",
    "register_alpaca_us_equity_assets",
    "resolve_alpaca_us_equity_registration_plan",
]
