"""migrate alpaca connector metatables to sdk8

Revision ID: 0001
Revises:
Create Date: 2026-09-02 13:52:34.884700

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__bars_1d_iex_raw",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("trade_count", sa.Float(), nullable=True),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__alpaca_connectors__bars_1d_iex_raw__asset_identi_ef75686ba4"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "alpaca_connectors",
            "namespace": "mainsequence.markets",
            "identifier": "alpaca_stock_bars_1d_iex_raw",
        },
    )
    op.create_index(
        "uix__alpaca_connectors__bars_1d_iex_raw__time_index_6664d2ba35",
        "alpaca_connectors__bars_1d_iex_raw",
        ["time_index", "asset_identifier"],
        unique=True,
    )
    op.create_table(
        "alpaca_connectors__bars_1d_sip_all",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("trade_count", sa.Float(), nullable=True),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__alpaca_connectors__bars_1d_sip_all__asset_identi_7746ed8e37"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "alpaca_connectors",
            "namespace": "mainsequence.markets",
            "identifier": "alpaca_stock_bars_1d_sip_all",
        },
    )
    op.create_index(
        "uix__alpaca_connectors__bars_1d_sip_all__time_index_b85bcf43d9",
        "alpaca_connectors__bars_1d_sip_all",
        ["time_index", "asset_identifier"],
        unique=True,
    )
    op.create_table(
        "alpaca_connectors__acct_alpaca",
        sa.Column("account_uid", sa.Uuid(), nullable=False),
        sa.Column("account_unique_identifier", sa.String(length=255), nullable=False),
        sa.Column("alpaca_account_id", sa.String(length=64), nullable=False),
        sa.Column("account_number", sa.String(length=64), nullable=False),
        sa.Column("api_key_fingerprint", sa.String(length=32), nullable=False),
        sa.Column("is_paper", sa.Boolean(), nullable=False),
        sa.Column("snapshot_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("crypto_status", sa.String(length=32), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("multiplier", sa.String(length=8), nullable=True),
        sa.Column("pattern_day_trader", sa.Boolean(), nullable=True),
        sa.Column("daytrade_count", sa.Integer(), nullable=True),
        sa.Column("shorting_enabled", sa.Boolean(), nullable=True),
        sa.Column("trading_blocked", sa.Boolean(), nullable=True),
        sa.Column("transfers_blocked", sa.Boolean(), nullable=True),
        sa.Column("account_blocked", sa.Boolean(), nullable=True),
        sa.Column("trade_suspended_by_user", sa.Boolean(), nullable=True),
        sa.Column("options_approved_level", sa.Integer(), nullable=True),
        sa.Column("options_trading_level", sa.Integer(), nullable=True),
        sa.Column("balance_asof", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dtbp_check", sa.String(length=8), nullable=True),
        sa.Column("pdt_check", sa.String(length=8), nullable=True),
        sa.Column("fractional_trading", sa.Boolean(), nullable=True),
        sa.Column("max_margin_multiplier", sa.String(length=8), nullable=True),
        sa.Column("no_shorting", sa.Boolean(), nullable=True),
        sa.Column("suspend_trade", sa.Boolean(), nullable=True),
        sa.Column("trade_confirm_email", sa.String(length=8), nullable=True),
        sa.Column("max_options_trading_level", sa.Integer(), nullable=True),
        sa.Column("raw_account_payload", sa.JSON(), nullable=True),
        sa.Column("cash", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("equity", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("last_equity", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("long_market_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("short_market_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("position_market_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("regt_buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("daytrading_buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("non_marginable_buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("options_buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("effective_buying_power", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("bod_dtbp", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("initial_margin", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("maintenance_margin", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("last_maintenance_margin", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("sma", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("accrued_fees", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("pending_reg_taf_fees", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("pending_transfer_in", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("pending_transfer_out", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("intraday_adjustments", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_uid"],
            ["ms_markets__account.uid"],
            name=op.f("fk__alpaca_connectors__acct_alpaca__account_uid__ms_74809e172f"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_uid", name=op.f("pk__alpaca_connectors__acct_alpaca")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AlpacaAccountDetails",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__acct_alpaca__api_key_fingerprint"),
        "alpaca_connectors__acct_alpaca",
        ["api_key_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__acct_alpaca__account_unique_identifier"),
        "alpaca_connectors__acct_alpaca",
        ["account_unique_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__acct_alpaca__alpaca_account_id"),
        "alpaca_connectors__acct_alpaca",
        ["alpaca_account_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix__alpaca_connectors__acct_alpaca__alpaca_account_id"),
        table_name="alpaca_connectors__acct_alpaca",
    )
    op.drop_index(
        op.f("uix__alpaca_connectors__acct_alpaca__account_unique_identifier"),
        table_name="alpaca_connectors__acct_alpaca",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__acct_alpaca__api_key_fingerprint"),
        table_name="alpaca_connectors__acct_alpaca",
    )
    op.drop_table("alpaca_connectors__acct_alpaca")
    op.drop_index(
        "uix__alpaca_connectors__bars_1d_sip_all__time_index_b85bcf43d9",
        table_name="alpaca_connectors__bars_1d_sip_all",
    )
    op.drop_table("alpaca_connectors__bars_1d_sip_all")
    op.drop_index(
        "uix__alpaca_connectors__bars_1d_iex_raw__time_index_6664d2ba35",
        table_name="alpaca_connectors__bars_1d_iex_raw",
    )
    op.drop_table("alpaca_connectors__bars_1d_iex_raw")
    # ### end Alembic commands ###
