"""store alpaca bar configurations

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-03 11:27:22.248794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, Sequence[str], None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__bars_configuration",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("account_uid", sa.Uuid(), nullable=False),
        sa.Column("asset_source", sa.String(length=32), nullable=False),
        sa.Column("universe_uid", sa.Uuid(), nullable=True),
        sa.Column("frequency_id", sa.String(length=16), nullable=False),
        sa.Column("feed", sa.String(length=16), nullable=False),
        sa.Column("adjustment", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(asset_source = 'universe' AND universe_uid IS NOT NULL) OR (asset_source <> 'universe' AND universe_uid IS NULL)",
            name=op.f("ck__alpaca_connectors__bars_configuration__ck_alpaca_a7f554576d"),
        ),
        sa.CheckConstraint(
            "asset_source IN ('assets', 'universe', 'account_holdings')",
            name=op.f("ck__alpaca_connectors__bars_configuration__ck_alpaca_4aa4463518"),
        ),
        sa.ForeignKeyConstraint(
            ["account_uid"],
            ["ms_markets__account.uid"],
            name=op.f("fk__alpaca_connectors__bars_configuration__account_u_ccd74cf5a7"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["universe_uid"],
            ["ms_markets__assetcategory.uid"],
            name=op.f("fk__alpaca_connectors__bars_configuration__universe_f2b6134ead"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk__alpaca_connectors__bars_configuration")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AlpacaBarsConfiguration",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__bars_configuration__account_uid"),
        "alpaca_connectors__bars_configuration",
        ["account_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__bars_configuration__asset_source"),
        "alpaca_connectors__bars_configuration",
        ["asset_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__bars_configuration__enabled"),
        "alpaca_connectors__bars_configuration",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__bars_configuration__name"),
        "alpaca_connectors__bars_configuration",
        ["name"],
        unique=False,
    )
    op.create_table(
        "alpaca_connectors__bars_configuration_asset",
        sa.Column("configuration_uid", sa.Uuid(), nullable=False),
        sa.Column("asset_uid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_uid"],
            ["ms_markets__asset.uid"],
            name=op.f("fk__alpaca_connectors__bars_configuration_asset__ass_a2cedbbbf5"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["configuration_uid"],
            ["alpaca_connectors__bars_configuration.uid"],
            name=op.f("fk__alpaca_connectors__bars_configuration_asset__con_3c5d126066"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "configuration_uid",
            "asset_uid",
            name=op.f("pk__alpaca_connectors__bars_configuration_asset"),
        ),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AlpacaBarsConfigurationAsset",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__bars_configuration_asset__asset_uid"),
        "alpaca_connectors__bars_configuration_asset",
        ["asset_uid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__alpaca_connectors__bars_configuration_asset__asset_uid"),
        table_name="alpaca_connectors__bars_configuration_asset",
    )
    op.drop_table("alpaca_connectors__bars_configuration_asset")
    op.drop_index(
        op.f("ix__alpaca_connectors__bars_configuration__name"),
        table_name="alpaca_connectors__bars_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__bars_configuration__enabled"),
        table_name="alpaca_connectors__bars_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__bars_configuration__asset_source"),
        table_name="alpaca_connectors__bars_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__bars_configuration__account_uid"),
        table_name="alpaca_connectors__bars_configuration",
    )
    op.drop_table("alpaca_connectors__bars_configuration")
    # ### end Alembic commands ###
