"""add asset universe registry

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-03 22:39:54.052804

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__asset_universe",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("source_uid", sa.Uuid(), nullable=False),
        sa.Column("asset_category_uid", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_category_uid"],
            ["ms_markets__assetcategory.uid"],
            name=op.f("fk__alpaca_connectors__asset_universe__asset_categor_8bf394f434"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_uid"],
            ["alpaca_connectors__universe_source.uid"],
            name=op.f("fk__alpaca_connectors__asset_universe__source_uid__a_116b545a8a"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk__alpaca_connectors__asset_universe")),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AssetUniverse",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_universe__is_active"),
        "alpaca_connectors__asset_universe",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__asset_universe__asset_category_uid"),
        "alpaca_connectors__asset_universe",
        ["asset_category_uid"],
        unique=True,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__asset_universe__source_uid"),
        "alpaca_connectors__asset_universe",
        ["source_uid"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk__alpaca_connectors__bars_configuration__universe_f2b6134ead"),
        "alpaca_connectors__bars_configuration",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__alpaca_connectors__bars_configuration__universe_a0233ca8ac"),
        "alpaca_connectors__bars_configuration",
        "alpaca_connectors__asset_universe",
        ["universe_uid"],
        ["uid"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk__alpaca_connectors__bars_configuration__universe_a0233ca8ac"),
        "alpaca_connectors__bars_configuration",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk__alpaca_connectors__bars_configuration__universe_f2b6134ead"),
        "alpaca_connectors__bars_configuration",
        "ms_markets__assetcategory",
        ["universe_uid"],
        ["uid"],
        ondelete="RESTRICT",
    )
    op.drop_index(
        op.f("uix__alpaca_connectors__asset_universe__source_uid"),
        table_name="alpaca_connectors__asset_universe",
    )
    op.drop_index(
        op.f("uix__alpaca_connectors__asset_universe__asset_category_uid"),
        table_name="alpaca_connectors__asset_universe",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_universe__is_active"),
        table_name="alpaca_connectors__asset_universe",
    )
    op.drop_table("alpaca_connectors__asset_universe")
    # ### end Alembic commands ###
