"""remove universe account assignment

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-03 23:48:52.098808

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: Union[str, Sequence[str], None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix__alpaca_connectors__asset_universe__account_uid"),
        table_name="alpaca_connectors__asset_universe",
    )
    op.drop_constraint(
        op.f("fk__alpaca_connectors__asset_universe__account_uid_13e7cad5ea"),
        "alpaca_connectors__asset_universe",
        type_="foreignkey",
    )
    op.drop_column("alpaca_connectors__asset_universe", "account_uid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alpaca_connectors__asset_universe",
        sa.Column("account_uid", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk__alpaca_connectors__asset_universe__account_uid_13e7cad5ea"),
        "alpaca_connectors__asset_universe",
        "ms_markets__account",
        ["account_uid"],
        ["uid"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("ix__alpaca_connectors__asset_universe__account_uid"),
        "alpaca_connectors__asset_universe",
        ["account_uid"],
        unique=False,
    )
    # ### end Alembic commands ###
