"""add durable ETF portfolio configurations

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-05 16:36:17.217468

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, Sequence[str], None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alpaca_connectors__portfolio_rebalance_configuration",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "strategy = 'immediate_signal'",
            name=op.f("ck__alpaca_connectors__portfolio_rebalance_configura_d2697beab2"),
        ),
        sa.PrimaryKeyConstraint(
            "uid", name=op.f("pk__alpaca_connectors__portfolio_rebalance_configuration")
        ),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "PortfolioRebalanceConfiguration",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__portfolio_rebalance_configura_cf6030e0fc"),
        "alpaca_connectors__portfolio_rebalance_configuration",
        ["strategy"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__portfolio_rebalance_configuration__name"),
        "alpaca_connectors__portfolio_rebalance_configuration",
        ["name"],
        unique=False,
    )
    op.create_table(
        "alpaca_connectors__etf_portfolio_configuration",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("signal_configuration_uid", sa.Uuid(), nullable=False),
        sa.Column("bars_configuration_uid", sa.Uuid(), nullable=False),
        sa.Column("rebalance_configuration_uid", sa.Uuid(), nullable=False),
        sa.Column("portfolio_uid", sa.Uuid(), nullable=True),
        sa.Column("job_uid", sa.Uuid(), nullable=True),
        sa.Column("upsample_frequency_id", sa.String(length=16), nullable=False),
        sa.Column("intraday_bar_interpolation_rule", sa.String(length=16), nullable=False),
        sa.Column("valuation_column", sa.String(length=64), nullable=False),
        sa.Column("portfolio_prices_frequency", sa.String(length=16), nullable=True),
        sa.Column("forward_fill_to_now", sa.Boolean(), nullable=False),
        sa.Column("fail_on_missing_prices", sa.Boolean(), nullable=False),
        sa.Column("commission_fee", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intraday_bar_interpolation_rule = 'ffill'",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_081735bbf6"),
        ),
        sa.CheckConstraint(
            "portfolio_prices_frequency IS NULL OR portfolio_prices_frequency = '1d'",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_0251d16f17"),
        ),
        sa.CheckConstraint(
            "upsample_frequency_id = '1d'",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_a1c4d4a0f0"),
        ),
        sa.CheckConstraint(
            "commission_fee >= 0",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_b1ac7aaa76"),
        ),
        sa.CheckConstraint(
            "length(trim(intraday_bar_interpolation_rule)) > 0",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_d641612457"),
        ),
        sa.CheckConstraint(
            "length(trim(upsample_frequency_id)) > 0",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_e79d7c21d6"),
        ),
        sa.CheckConstraint(
            "length(trim(valuation_column)) > 0",
            name=op.f("ck__alpaca_connectors__etf_portfolio_configuration_1079d6402e"),
        ),
        sa.ForeignKeyConstraint(
            ["bars_configuration_uid"],
            ["alpaca_connectors__bars_configuration.uid"],
            name=op.f("fk__alpaca_connectors__etf_portfolio_configuration_d7050e3846"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_uid"],
            ["ms_markets__portfolio.uid"],
            name=op.f("fk__alpaca_connectors__etf_portfolio_configuration_d1e5d9a31d"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rebalance_configuration_uid"],
            ["alpaca_connectors__portfolio_rebalance_configuration.uid"],
            name=op.f("fk__alpaca_connectors__etf_portfolio_configuration_0c3e4234aa"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_configuration_uid"],
            ["alpaca_connectors__etf_signal_job_configuration.uid"],
            name=op.f("fk__alpaca_connectors__etf_portfolio_configuration_8c86b51e46"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "uid", name=op.f("pk__alpaca_connectors__etf_portfolio_configuration")
        ),
        info={
            "namespace": "mainsequence.markets",
            "identifier": "AlpacaETFPortfolioConfiguration",
            "markets_storage_app": "alpaca_connectors",
        },
    )
    op.create_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_53174662de"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["signal_configuration_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration__name"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_d13119c5b7"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["bars_configuration_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_fb7a662c4d"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["rebalance_configuration_uid"],
        unique=False,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__etf_portfolio_configuration__job_uid"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["job_uid"],
        unique=True,
    )
    op.create_index(
        op.f("uix__alpaca_connectors__etf_portfolio_configuration_df075f07b6"),
        "alpaca_connectors__etf_portfolio_configuration",
        ["portfolio_uid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uix__alpaca_connectors__etf_portfolio_configuration_df075f07b6"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_index(
        op.f("uix__alpaca_connectors__etf_portfolio_configuration__job_uid"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_fb7a662c4d"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_d13119c5b7"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration__name"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__etf_portfolio_configuration_53174662de"),
        table_name="alpaca_connectors__etf_portfolio_configuration",
    )
    op.drop_table("alpaca_connectors__etf_portfolio_configuration")
    op.drop_index(
        op.f("ix__alpaca_connectors__portfolio_rebalance_configuration__name"),
        table_name="alpaca_connectors__portfolio_rebalance_configuration",
    )
    op.drop_index(
        op.f("ix__alpaca_connectors__portfolio_rebalance_configura_cf6030e0fc"),
        table_name="alpaca_connectors__portfolio_rebalance_configuration",
    )
    op.drop_table("alpaca_connectors__portfolio_rebalance_configuration")
    # ### end Alembic commands ###
