"""add Alpaca portfolio interpolated prices

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-05 21:56:54.315339

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, Sequence[str], None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ms_markets__interpolated_prices__t_0e9255594b348d8c",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("trade_count", sa.Float(), nullable=True),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.Column("interpolated", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__interpolated_prices__t_0e9255594b348_b89c349ad7"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "InterpolatedPricesTS",
        },
    )
    op.create_index(
        "uix__ms_markets__interpolated_prices__t_0e9255594b34_92891acd82",
        "ms_markets__interpolated_prices__t_0e9255594b348d8c",
        ["time_index", "asset_identifier"],
        unique=True,
    )
    op.create_table(
        "ms_markets__interpolated_prices__t_43b7a7a637ae4df3",
        sa.Column("time_index", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset_identifier", sa.String(length=255), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("trade_count", sa.Float(), nullable=True),
        sa.Column("vwap", sa.Float(), nullable=True),
        sa.Column("interpolated", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_identifier"],
            ["ms_markets__asset.unique_identifier"],
            name=op.f("fk__ms_markets__interpolated_prices__t_43b7a7a637ae4_351f72ebf0"),
            ondelete="RESTRICT",
        ),
        info={
            "markets_storage_app": "ms_markets",
            "namespace": "mainsequence.markets",
            "identifier": "InterpolatedPricesTS",
        },
    )
    op.create_index(
        "uix__ms_markets__interpolated_prices__t_43b7a7a637ae_0f0a6341f0",
        "ms_markets__interpolated_prices__t_43b7a7a637ae4df3",
        ["time_index", "asset_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix__ms_markets__interpolated_prices__t_43b7a7a637ae_0f0a6341f0",
        table_name="ms_markets__interpolated_prices__t_43b7a7a637ae4df3",
    )
    op.drop_table("ms_markets__interpolated_prices__t_43b7a7a637ae4df3")
    op.drop_index(
        "uix__ms_markets__interpolated_prices__t_0e9255594b34_92891acd82",
        table_name="ms_markets__interpolated_prices__t_0e9255594b348d8c",
    )
    op.drop_table("ms_markets__interpolated_prices__t_0e9255594b348d8c")
    # ### end Alembic commands ###
