"""Asset registration helpers for Alpaca connectors."""

from etf_extraction.extractors import (
    ExpandedSymbolUniverse,
    InvescoHoldingsExtractor,
    IsharesHoldingsExtractor,
    StateStreetHoldingsExtractor,
    VanguardHoldingsExtractor,
    build_component_extractor,
    fetch_invesco_component_tickers,
    fetch_ishares_component_tickers,
    fetch_page_html_with_playwright,
    fetch_state_street_component_tickers,
    fetch_vanguard_component_tickers,
    parse_ishares_holdings_tickers,
)
from .alpaca_us_equities import (
    AlpacaEquityClassificationPass,
    AlpacaEquityRegistrationPlan,
    AlpacaEquityRegistrationResolution,
    AlpacaUsEquity,
    OpenFigiMatch,
    build_alpaca_us_equity_registration_plan,
    build_alpaca_us_equity_trading_client,
    classify_alpaca_us_equities,
    fetch_alpaca_us_equities,
    query_openfigi_by_ticker,
    register_alpaca_us_equity_assets,
    resolve_alpaca_us_equity_registration_plan,
)

__all__ = [
    "AlpacaEquityClassificationPass",
    "AlpacaEquityRegistrationPlan",
    "AlpacaEquityRegistrationResolution",
    "AlpacaUsEquity",
    "ExpandedSymbolUniverse",
    "InvescoHoldingsExtractor",
    "IsharesHoldingsExtractor",
    "OpenFigiMatch",
    "StateStreetHoldingsExtractor",
    "VanguardHoldingsExtractor",
    "build_component_extractor",
    "build_alpaca_us_equity_registration_plan",
    "build_alpaca_us_equity_trading_client",
    "classify_alpaca_us_equities",
    "fetch_alpaca_us_equities",
    "fetch_invesco_component_tickers",
    "fetch_ishares_component_tickers",
    "fetch_page_html_with_playwright",
    "fetch_state_street_component_tickers",
    "fetch_vanguard_component_tickers",
    "parse_ishares_holdings_tickers",
    "query_openfigi_by_ticker",
    "register_alpaca_us_equity_assets",
    "resolve_alpaca_us_equity_registration_plan",
]
